### PR TITLE
2014 04 10

### PR DESCRIPTION
**Pull request by Jordann**
## 2014 04 10

I've been reading up a lot on how we can interweave Angular and Backbone. It's hard to get a good grasp on the advantages and disadvantages, when I don't have a huge familiarity with either.

Also I'm going to begin writing some more advanced tests, I'll probably do those later on tonight

### CODE REVIEW

**Comment by howardroark** [comment]
Yes, I imagine it will not be simple.  Though we have a logical intent, and we really just need to be able to accomplish it.  Backbone is extremely flexible, it's really a matter of understanding how flexible Angular can be.  Maybe we can stick with Angular only, but this seems like a good way to help us learn a lesson.

**Comment by howardroark** [comment]
I noticed you just added backbone local storage.  I wast thinking this one may be more appropriate...

https://github.com/nilbus/Backbone.dualStorage

I will let you decide though.

**Comment by Jordann** [comment]
I was just going to try it out so i installed it. dual storage does seem better, though. I think I'll try that first

**Comment by howardroark** [comment]
Let me know when you are wrapped up for the day here so that I can merge this back into master.

**Comment by Jordann** [comment]
ok im probably going to do some test stuff tonight, but Ill just add that to tomorrows branch or something.

Im wrapped up for now

**Comment by howardroark** [comment]
How about when you wrap up just complete the pull request.

**Pull request merged**
